config/routes.rb
Rails.application.routes.draw do

  resources :quizzes

  resources :quiz_questions, only: [], param: :index do
    member do
      delete '(:id)' => "quiz_questions#destroy", as: ""
      post '/' => "quiz_questions#create"
    end
  end

  resources :surveys

  resources :survey_questions, only: [], param: :index do
    member do
      delete '(:id)' => "survey_questions#destroy", as: ""
      post '/' => "survey_questions#create"
    end
  end

  resources :questions do
      get "search_by", on: :collection
  end

  root "pages#home"
end

app/models/question.rb
class Question < ApplicationRecord
    #Base Question Validation
    has_many :quiz_questions
    has_many :quiz, :through => :quiz_questions
    has_rich_text :title
    validates :question_type, :title, :bank, presence: true
    enum question_type: {
        true_false: "true_false",
        multiple_choice: "multiple_choice", 
        multiple_answers: "multiple_answers",
        essay: "essay",
        matching: "matching"
    }

    #For when user creates a new bank on question
    attr_accessor :new_bank

    #Multiple Choice Validation
    has_many :multiple_choices, inverse_of: :question, dependent: :destroy
    accepts_nested_attributes_for :multiple_choices, reject_if: :not_multiple_choice?, allow_destroy: true

    #True False Validation
    has_one :true_false, inverse_of: :question, dependent: :destroy
    accepts_nested_attributes_for :true_false, reject_if: :not_true_false?, allow_destroy: true

    #Multiple Answers Validation
    has_many :multiple_answers, inverse_of: :question, dependent: :destroy
    accepts_nested_attributes_for :multiple_answers, reject_if: :not_multiple_answers?

    #Multiple Answers Validation
    has_one :matching, inverse_of: :question, dependent: :destroy
    accepts_nested_attributes_for :matching, reject_if: :not_matchings?

    #Quiz Question Assocations
    has_many :quizzes, through: :quiz_questions
    has_many :quiz_questions, dependent: :destroy

    #Survey Question Assocations
    has_many :surveys, through: :survey_questions
    has_many :survey_questions, dependent: :destroy
    
    private 
    #Question Type Checkers
    def not_multiple_choice?
        question_type != 'multiple_choice' 
    end

    def not_true_false?
        question_type != 'true_false'
    end

    def not_multiple_answers?
        question_type != 'multiple_answers' 
    end

     def not_matchings?
        question_type != 'matching' 
    end

     
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.order(:bank)
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    build_multiple_choice(4)
    build_multiple_answers(4)
    @question.build_matching
    @question.build_true_false
    @list = [] 
    @answer=[]
  end

  # GET /questions/1/edit
  def edit
    @question.new_bank = nil
     @list=[]
     if @question.matching? then 
      @list.push @question.matching.choice_1
       @list.push  @question.matching.choice_2
        @list.push @question.matching.choice_3
         @list.push @question.matching.choice_4
     end
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

      if params[:question][:new_bank].present?
        @question.bank = params[:question][:new_bank]
      end

      @question.bank =  @question.bank.downcase

     
      @answer=[]
      @answer.push params[:question][:matching_attributes][:answer_1]
       @answer.push params[:question][:matching_attributes][:answer_2]
        @answer.push params[:question][:matching_attributes][:answer_3]
         @answer.push params[:question][:matching_attributes][:answer_4]

      @list=[]
      @list.push params[:question][:matching_attributes][:choice_1]
       @list.push params[:question][:matching_attributes][:choice_2]
        @list.push params[:question][:matching_attributes][:choice_3]
         @list.push params[:question][:matching_attributes][:choice_4]

         puts @list

         puts params[:question][:matching_attributes]
      puts "###############################################"
    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_url, notice: "Question was successfully created." }
        format.json { render :index, status: :created, location: @question }
      else

        unless @question.multiple_choice? then
          build_multiple_choice(4)
        end

        unless @question.multiple_answers? then
          build_multiple_answers(4)
        end

        unless @question.matching? then
          @question.build_matching
        end
           
        @question.build_true_false

        @list;
        @answer
         
         format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update

    if params[:question][:new_bank].present?
        params[:question][:bank] = params[:question][:new_bank]
    end

    @list=[]
      @list.push params[:question][:matching_attributes][:choice_1]
       @list.push params[:question][:matching_attributes][:choice_2]
        @list.push params[:question][:matching_attributes][:choice_3]
         @list.push params[:question][:matching_attributes][:choice_4]
    
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to questions_url, notice: "Question was successfully updated." }
        format.json { render :index, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #GET searches questions by bank
  def search_by
    @questions = if !params[:search_by_bank].blank? && !params[:search_by_question_type].blank?
      Question.where(bank: params[:search_by_bank], question_type: params[:search_by_question_type])
    elsif !params[:search_by_bank].blank? && params[:search_by_question_type].blank?
         Question.where(bank: params[:search_by_bank])
    elsif params[:search_by_bank].blank? && !params[:search_by_question_type].blank?
         Question.where(question_type: params[:search_by_question_type])
    else
      Question.all
    end
    render 'index'

    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:id, :title, :question_type, :bank, :new_bank,
        multiple_choices_attributes: [:id, :option, :is_correct, :_destroy], 
        true_false_attributes: [:id, :correct_answer],
        multiple_answers_attributes: [:id, :option, :is_correct, :_destroy],
        matching_attributes: [:id, :prompt_1, :prompt_2, :prompt_3,  :prompt_4, :answer_1, :answer_2, :answer_3, :answer_4,
        :choice_1,  :choice_2, :choice_3, :choice_4, :_destroy],
        bank_attributes: [:bank] )
    end

    def build_multiple_choice(num)
      num.times { @question.multiple_choices.build }
    end

    def build_multiple_answers(num)
      num.times { @question.multiple_answers.build }
    end

    def build_matching(num)
      num.times { @question.matchings.build }
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for question do |f| %>
  <% if question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%#Question Title%>
  <div class="border  rounded px-4 pb-4 pt-2">
    <%= f.label :title,"Question:", { style: "display: block", for: "question_title_trix_input_question_#{question.id}",  class: "fs-4 form-label"} %>
    <%= f.rich_text_area :title, class: "form-control border border-secondary-subtle", placeholder: "Type your question here" %>
  </div>

  <%#Question Bank Fields%>
  <div class="row align-items-center mt-4">
    <div class="col">
      <%= f.label :bank, 'Existing Question Bank', style: "display: block", class: "form-label fs-5"%>
    <%= f.select :bank, Question.group(:bank).map {|question| [question.bank.titleize, question.bank]},
    { include_blank: "Choose an existing question bank"}, {class: "form-select border border-secondary-subtle"}%>
    </div>
    <div class="col-12 text-center col-md-1 my-3">
    <p class="m-0 fw-light text-secondary">OR</p>
    </div>
    <div class="col-12 col-md">
      <%= f.label :new_bank, 'New Question Bank', style: "display: block", class: "form-label fs-5" %>
      <%= f.text_field :new_bank, class: "form-control border border-secondary-subtle", placeholder: "Create a new question bank" %>
    </div>   
  </div>

  <%#Question Type Select%>
  <div class="row my-4"> 
    <% unless Question.where(id: question.id).exists? then %> 
      <div class="col-md-5 col-12">
        <%= f.label :question_type, {style: "display: block", for: "question-type-selection", class: "form-label fs-5" }  %>
        <%= f.select :question_type, Question.question_types.map { |key, value|  [key.titleize, key]},
        { include_blank: "Select a Question Type:"}, { id: "question-type-selection", onChange: "changeNestedForm(event)", 
        class: "form-control border border-secondary-subtle"} %>
      </div>
    <% else %>
      <div class="col">
        <p class="m-0 fs-4">
        <strong>Question Type:</strong>
        <%= question.question_type.titleize %>
        </p>
      </div>
    <% end %>
  </div> 
  <hr>

  <%#Different Form Renders%>
  <div class="row">

    <%#Multiple Choice Render%>
    <div id="mc-form" <% unless question.question_type == 'multiple_choice' then %>
      style="display: none"
    <% end %> >
      <div class="row">
        <%= f.fields_for :multiple_choices do |multiple_choice_form| %>
          <%= render "multiple_choice_fields", f: multiple_choice_form %>
        <%end%>
      </div>
      <hr class="my-4">
    </div>

    <%#Multiple Answer Render%>
    <div id="ma-form" <% unless question.question_type == 'multiple_answers' then %>
      style="display: none"
    <% end %> >
      <div class="row">
        <%= f.fields_for :multiple_answers do |multiple_answer_form| %>
          <%= render "multiple_answer_fields", f: multiple_answer_form %>
        <%end%>
      </div>
      <hr class="my-4">
    </div>

    <%#True False Render%>
    <div id="tf-form" <% unless question.question_type == 'true_false' then %>
      style="display: none"
    <% end %> >
      <%= f.fields_for :true_false do |true_false_form| %>
          <%= render "true_false_fields", f: true_false_form %>
      <%end%>
      <hr class="my-4">
    </div>

    <%#Matching Render%>
    <div id="match-form" <% unless question.question_type == 'matching' then %>
      style="display: none"
    <% end %> >
      <%= f.fields_for :matching do |matching| %>
          <%= render "matching_fields", f: matching %>
      <%end%>
      <hr class="my-4">
    </div>

  </div>
  <%#Form Submission%>
  <div class="mt-4 mb-5">
    <%= f.submit class: "btn btn-primary fs-4 py-2"%>
  </div>
<% end %>


<%#Form Scripts %>
<%= javascript_include_tag "multiple_choice.js" %>

<%#Question type selection change script %>
<% unless Question.where(id: question.id).exists? then %> 
 <%= javascript_include_tag "question_types.js" %>
<% end %>

<script>
</script>

app/views/questions/_matching_fields.html.erb
<div class="row">
    <div class="row col-12 col-md-6 mb-5">
        <div class="col-12">
            <%= f.label :prompt_1, style: "display: block", class: "form-label fs-5"%>
            <%= f.text_field :prompt_1 , class: "form-control border border-secondary-subtle"%> 
        </div>

        <div class="col-12">
            <%= f.label :answer_1, style: "display: block", class: "form-label fs-5"%>
            <%= f.select :answer_1, ([["Choose Matching Answer", nil]] + @list.map { |item| [item, item]}), {}, {class: "matching-select form-control border border-secondary-subtle"}%>
            <p class="text-secondary m-0 ms-2">Type in choices to populate answers</p>
        </div>    
    </div>

    <div class="row col-12 col-md-6 mb-5">
        <div class="col-12">
            <%= f.label :prompt_2, style: "display: block", class: "form-label fs-5"%>
            <%= f.text_field :prompt_2 , class: "form-control border border-secondary-subtle"%> 
        </div>

        <div class="col-12">
            <%= f.label :answer_2, style: "display: block", class: "form-label fs-5"%>
            <%= f.select :answer_2, ([["Choose Matching Answer", nil]] + @list.map { |item| [item, item]}), {}, {class: "matching-select form-control border border-secondary-subtle"}%>
            <p class="text-secondary m-0 ms-2">Type in choices to populate answers</p>
        </div>    
    </div>

    <div class="row col-12 col-md-6 mb-5">
        <div class="col-12">
            <%= f.label :prompt_3, style: "display: block", class: "form-label fs-5"%>
            <%= f.text_field :prompt_3 , class: "form-control border border-secondary-subtle"%> 
        </div>

        <div class="col-12">
            <%= f.label :answer_3, style: "display: block", class: "form-label fs-5"%>
            <%= f.select :answer_3, ([["Choose Matching Answer", nil]] + @list.map { |item| [item, item]}), {}, {class: "matching-select form-control border border-secondary-subtle"}%>
            <p class="text-secondary m-0 ms-2">Type in choices to populate answers</p>
        </div>    
    </div>

    <div class="row col-12 col-md-6 mb-5">
        <div class="col-12">
            <%= f.label :prompt_4, style: "display: block", class: "form-label fs-5"%>
            <%= f.text_field :prompt_4 , class: "form-control border border-secondary-subtle"%> 
        </div>

        <div class="col-12">
            <%= f.label :answer_4, style: "display: block", class: "form-label fs-5"%>
            <%= f.select :answer_4, ([["Choose Matching Answer", nil]] + @list.map { |item| [item, item]}), {}, {class: "matching-select form-control border border-secondary-subtle"}%>
            <p class="text-secondary m-0 ms-2">Type in choices to populate answers</p>
        </div>    
    </div>
</div>

<div class="row justify-content-center mt-2">
    <h3 class="text-center mb-3 fs-1">Choices</h3>
    <div class="col-12 col-md-5 mb-4">
        <%=f.label :choice_1, style: "display: block", class: "form-label fs-5"%>
        <%= f.text_field :choice_1, onChange: "addThis(event, 0)", class: "matching-choice form-control border border-secondary-subtle"%>
    </div>
    <div class="col-12 col-md-5 mb-4">
        <%=f.label :choice_2, style: "display: block", class: "form-label fs-5"%>
         <%= f.text_field :choice_2, onChange: "addThis(event, 1)", class: "matching-choice form-control border border-secondary-subtle"%>
    </div>
        
    <div class="col-12 col-md-5 mb-4">
        <%=f.label :choice_3, style: "display: block", class: "form-label fs-5"%>
        <%= f.text_field :choice_3, onChange: "addThis(event, 2)", class: "matching-choice form-control border border-secondary-subtle"%> 
    </div>
    <div class="col-12 col-md-5 mb-4">
        <%=f.label :choice_4, style: "display: block", class: "form-label fs-5"%>
        <%= f.text_field :choice_4, onChange: "addThis(event, 3)", class: "matching-choice form-control border border-secondary-subtle"%>
    </div>
     
</div>

<script>
    function addThis(event, choice) {
        const answerSelect = document.querySelectorAll(".matching-select");
        const choices = document.querySelectorAll(".matching-choice");

        const saveChoice = []
        choices.forEach(choiceID => {
                saveChoice.push(choiceID.value)
        })

        answerSelect.forEach(select => {
            select.options.length = 1;
            saveChoice.forEach(item => {
                if(item.trim().length >= 1)
                    select.options.add(new Option(item, item))
            })
        })
            
    }
</script>

app/views/questions/_matching_show.html.erb
<div class="row">
    <div class="col-md-6 col-12">

        <h3 class="text-center">Prompts/Answers</h3>
        <hr>
        <div class="row justify-content-center align-items-center">
            <p class="col-12 col-md-5 p-0 mx-0 fs-4 text-md-end pe-4"><%= question.matching.prompt_1%>:</p>
            <div class=" alert alert-success col col-md-5 text-center px-1">
                <p class="mb-0"><%= question.matching.answer_1%></p>
            </div>
        </div>

        <div class="row justify-content-center align-items-center">
            <p class="col-12 col-md-5 p-0 mx-0 fs-4 text-md-end pe-4"><%= question.matching.prompt_2%>:</p>
            <div class=" alert alert-success col col-md-5 text-center px-1">
                <p class="mb-0"><%= question.matching.answer_2%></p>
            </div>
        </div>

        <div class="row justify-content-center align-items-center">
            <p class="col-12 col-md-5 p-0 mx-0 fs-4 text-md-end pe-4"><%= question.matching.prompt_3%>:</p>
            <div class=" alert alert-success col col-md-5 text-center px-1">
                <p class="mb-0"><%= question.matching.answer_3%></p>
            </div>
        </div>

        <div class="row justify-content-center align-items-center">
            <p class="col-12 col-md-5 p-0 mx-0 fs-4 text-md-end pe-4"><%= question.matching.prompt_4%>:</p>
            <div class=" alert alert-success col col-md-5 text-center px-1">
                <p class="mb-0"><%= question.matching.answer_4%></p>
            </div>
        </div>
    </div>



    <div class="col-md-6 col-12">
        <h3 class="text-center">Choices</h3>
        <hr>
        <ul>
            <li class="list-group-item fs-4 text-center mb-2"><%= question.matching.choice_1%></li>
            <li class="list-group-item fs-4 text-center mb-2"><%= question.matching.choice_2%></li>
            <li class="list-group-item fs-4 text-center mb-2"><%= question.matching.choice_3%></li>
            <li class="list-group-item fs-4 text-center mb-2"><%= question.matching.choice_4%></li>
        </ul>
    </div>
</div>

app/views/questions/_multiple_answer_fields.html.erb
<div class="d-flex align-items-end col-md-6 px-4 col-12">
  <div class="me-3">
    
    <%= f.check_box :is_correct, {class: 'btn-check'} %>
    <%= f.label :is_correct,  "Correct Answer?", style: "display:block", class: "btn btn-outline-success"%>
  </div>

  <div class="flex-grow-1">
    <%= f.label :option, "Option #{f.index + 1}:",  style:"display: block", class: "form-label fs-5"%>
    <%= f.text_field :option, class: "form-control border border-secondary-subtle flex-grow-2"%>
  </div>
</div>

app/views/questions/_multiple_choice_fields.html.erb
<div class="d-flex align-items-end col-md-6 px-4 col-12">
  <div class="me-3">
    
    <%= f.check_box :is_correct, {class: 'mc-option btn-check'} %>
    <%= f.label :is_correct,  "Correct Answer?", style: "display: block", class: "btn btn-outline-success"%>
  </div> 

  <div class="flex-grow-1">
    <%= f.label :option, "Option #{f.index + 1}:",  style:"display: block", class: "form-label fs-5"%>
    <%= f.text_field :option, class: "form-control border border-secondary-subtle flex-grow-2"%>
  </div>
</div>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">

  <!-- Question Bank and Type -->
  <div class="d-flex justify-content-end pt-3 text-secondary" >
    <p>
      <strong>Question Type:</strong>
      <%= question.question_type.titleize %>
    </p>
    <p class="ms-5">
      <strong>Question Bank:</strong>
      <%= question.bank.titleize %>
    </p>
  </div>
  
  <!-- Question Title -->
  <div class="py-4">
    <h2>Question:</h2>
    <div class="fs-4">
      <%= question.title %>
    </div>
  </div>

  <!-- Question Type Display -->
  <div class= "p-3">
    <% if question.true_false? %>
       <div class="alert <%= question.true_false.correct_answer? ? 'alert-success fw-bold' : 'alert-secondary' %>">
        True  
      </div>
      <div class="alert <%= question.true_false.correct_answer? ? 'alert-secondary' : 'alert-success fw-bold' %>">
        False 
      </div>
    <% end %>
 
    <% if question.multiple_choice? %>
      <% question.multiple_choices.each do |choice| %>
        <!-- questions/question_option for when it's rendered in quizzes -->
        <%= render "questions/question_option", choice: choice %>
      <% end %>
    <% end %>

    <% if question.multiple_answers? %>
      <% question.multiple_answers.each do |answer| %>
        <!-- questions/question_option for when it's rendered in quizzes -->
        <%= render "questions/question_option", choice: answer %>
      <% end %>
    <% end %>

    <% if question.matching? %>
      <!-- questions/matching_show for when it's rendered in quizzes -->
      <%= render "questions/matching_show", question: question %>
    <% end %>
  </div>

  <!-- Edit and Delete Buttons -->
  <div class="d-flex justify-content-between align-items-end px-3 my-2 pb-4">
    <%= link_to edit_question_path(question), class: "btn btn-outline-primary px-5 mx-0 fs-4" do %> Edit <% end %>
    <%= button_to "Delete Question", question, method: :delete, class: " fs-5 fs-bold ms-auto btn btn-outline-danger py-0 px-2" %>
  </div>

</div>

app/views/questions/_question_option.html.erb
<div class="alert <%= choice.is_correct? ? 'alert-success fw-bold' : 'alert-secondary' %>">
  <p class="m-0"><%= choice.option %></p>
</div>

app/views/questions/_true_false_fields.html.erb
<p class="fs-5">Correct Answer:</p>
<div class="d-flex justify-content-start">
    <div class="me-2">
    <%= f.radio_button :correct_answer, true, class: "btn-check" %>
    <%= f.label :correct_answer_true, "True", class: "btn btn-outline-success px-4" %>
    </div>
    <div class="ms-2">
    
    <%= f.radio_button :correct_answer, false, class: "btn-check" %>
    <%= f.label :correct_answer_false, "False", class: "btn btn-outline-success px-4" %>
    </div>
</div>

app/views/questions/edit.html.erb
<div class="d-flex align-items-end pb-3 justify-content-between">
  <h1 class="m-0">Editing Question</h1>
  <div>
    <%= link_to questions_path, class: "btn btn-outline-primary" do %>
      <p class="m-0">Back to Questions</p>
    <% end %>
  </div>
</div>

<%= render "form", question: @question %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<div class="row pb-4 align-items-center">
  
  <div class="col my-5 my-md-0">
    <%= link_to "New Question", new_question_path , class: "col btn btn-primary fs-4"%>
  </div>
  
  <div class="col-lg-3 col-12">
    <%= form_with url: search_by_questions_url, method: :get, class: "form" do |f| %>
      <%#Question Bank Filter%>
      <div class="mb-2">
        <%= f.select :search_by_bank, options_for_select(
        [['All' , nil]] + Question.group(:bank).map {|question| [question.bank.titleize, question.bank]}, 
        selected: params[:search_by_bank]),
        { include_blank: "Search by Question Bank"}, {
         class: "form-select"} %>
      </div>

      <%#Question Type Filter%>
      <div class="mb-3">
         <%= f.select :search_by_question_type, options_for_select(
       [['All' , nil]] + Question.group(:question_type).map {|question| [question.question_type.titleize, question.question_type]}, 
       selected: params[:search_by_question_type]),
       { include_blank: "Search by Question Type"}, {
       class: "form-select"} %>
      </div>
      <%#Filter Submit%>
      <div class="d-flex justify-content-end">
         <%= f.submit 'Filter', class: "btn btn-outline-primary"%>
      </div>
    <% end %>

    <% unless params[:search_by_bank].blank? && params[:search_by_question_type].blank? %>
      <div class="d-flex  justify-content-end">
        <p class=" danger-emphasis mb-0 mt-3">
          <%= @questions.count %> result<%= (@questions.count > 1 || @questions.empty?) ? "s" : ""%> found
        </p>
      </div>
    <% end %>
  </div>
</div>


<p class="fs-5 text-success"><%= notice %></p>


<div id="questions" class="pb-5">
  <% @questions.each do |question| %>
  <hr>
    <%= render question %>
    
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="d-flex align-items-end pb-3 justify-content-between">
  <h1 class="m-0">New Question</h1>
  <div>
    <%= link_to questions_path, class: "btn btn-outline-primary" do %>
      <p class="m-0">Back to Questions</p>
    <% end %>
  </div>
</div>

<%= render "form", question: @question %>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>