config/routes.rb
Rails.application.routes.draw do

  resources :quizzes

  resources :quiz_questions, only: [], param: :index do
    member do
      delete '(:id)' => "quiz_questions#destroy", as: ""
      post '/' => "quiz_questions#create"
    end
  end

  resources :surveys

  resources :survey_questions, only: [], param: :index do
    member do
      delete '(:id)' => "survey_questions#destroy", as: ""
      post '/' => "survey_questions#create"
    end
  end

  resources :questions do
      get "search_by", on: :collection
  end

  root "pages#home"
end

app/models/survey_question.rb
class SurveyQuestion < ApplicationRecord
    belongs_to :survey
    belongs_to :question
  
    validates :question_id, presence: true;
  end
  

app/controllers/survey_questions_controller.rb
class SurveyQuestionsController < ApplicationController

    before_action :setup_survey_question

  def new
  end

  def destroy
  end

  private

    def setup_survey_question
      @survey = Survey.new(survey_questions: [SurveyQuestion.new])
      @questions = Question.all
    end
end

app/views/survey_questions/_form.html.erb
<%= form_with(model: survey_question) do |form| %>
  <% if survey_question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(survey_question.errors.count, "error") %> prohibited this survey_question from being saved:</h2>

       <%= form.select :question_id, @questions.map { |question| [question.title, question.id] }, { include_blank: "" }, { class: "form-select border border-secondary-subtle" } %>

      <ul>
        <% survey_question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :points, style: "display: block" %>
    <%= form.text_field :points %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/survey_questions/_survey_question.html.erb
<div id="<%= dom_id survey_question %>">
  <p>
    <strong>Points:</strong>
    <%= survey_question.points %>
  </p>

</div>

app/views/survey_questions/_survey_questions.html.erb
<%= turbo_frame_tag "survey_question_#{form.index}" do %>
  <%= form.hidden_field :id %>

  <script>
    function filterQuestions(index) {
    //Get values  from :question_bank select
    const selectedBank = document.getElementById("question-bank-select-" + index).value;

    //Get Select Element to replace with filtered info
    const questionSelect = document.getElementById("question-select-" + index);

    //Turn Question.all into JSON
    const questions = ("<%=  escape_javascript @questions.to_json %>");

    //Filter Text
    const filterText = questions.replace(/&quot;/ig, '"').replace(/&#39;/ig,"'").replace(/=&gt;/ig,':').replace(/\\u003c\/?[a-z]*\\u003e/ig,'')
    
    //Parse questions
    const questionsJSON = JSON.parse(filterText);
 

     let filteredQuestions = []

     //Question bank is true filter through said question bank
    if(selectedBank) {
      filteredQuestions = questionsJSON.filter(question => question.bank === selectedBank);
    }
    else{
      //Display all questions
      filteredQuestions = questionsJSON;
    }
     
    //Set question select to 1 for "blank" value
    questionSelect.options.length = 1;

    //Loops through to populate the select form
    filteredQuestions.forEach(question => 
        {questionSelect.options.add(new Option(question.title.body, question.id));
    });
  }
  </script>
  <div class="container mb-4 mt-5">
    <div class="d-flex flex-column flex-md-row">  
      <div class="">
        <span class="mb-4 fs-5 form-label me-3">Question Bank:</span>
      </div>  
      <div class="col-12 col-md-5 mb-4 col-lg-3">
        <%= select_tag :question_bank, options_for_select(@questions.group(:bank).map {|question| [question.bank.titleize, question.bank]}), {class: "form-select border border-secondary-subtle", id: "question-bank-select-#{form.index}", onChange: "filterQuestions(#{form.index})", include_blank: "All"} %>
      </div>
    </div>
    <div class="mb-4 col-12">
      <%= form.select :question_id, @questions.map {|question| [question.title, question.id]},
        { include_blank: "Choose A Question"}, {class: "form-select border border-secondary-subtle col-11", id: "question-select-#{form.index}"}%>
    </div>
  </div>
    
    

  <div class="d-flex justify-content-end mb-4 pt-4">
    <%= form.submit "Delete Question", 
          formaction: survey_question_path(form.index, form.object.id), 
          formmethod: :delete, 
          formnovalidate: true, 
          data: { turbo_frame: "survey_question_#{form.index}" },
          class: "btn btn-outline-danger " %>
  </div>  
  <hr>
      
<% end %>

app/views/survey_questions/create.turbo_stream.erb
<%# app/views/survey_questions/create.turbo_stream.erb %>
<%= fields model: @survey do |form| %>
  <%= form.fields_for :survey_questions, child_index: params[:index] do |sq_form| %>
    <%= turbo_stream.replace "add-survey-question" do %>
      <%= form.submit "Add Question", 
            class: "btn btn-outline-success",
            formaction: survey_question_path(sq_form.index.to_i + 1), 
            formmethod: :post, 
            formnovalidate: true, 
            id: "add-survey-question" %>
    <% end %>

    <%= turbo_stream.append "survey_questions" do %>
      <%= render "survey_questions", form: sq_form %>
    <% end %>
  <% end %>
<% end %>

app/views/survey_questions/destroy.html.erb
<%# app/views/survey_questions/destroy.html.slim %>
<%= fields model: @survey do |form| %>
  <%= form.fields_for :survey_questions, child_index: params[:index] do |qq_form| %>
    <%= turbo_frame_tag "survey_question_#{qq_form.index}" do %>
      <%= qq_form.hidden_field :id, value: params[:id] %>
      <%= qq_form.hidden_field :_destroy, value: true %>
    <% end %>
  <% end %>
<% end %>

app/views/survey_questions/edit.html.erb
<h1>Editing Survey Question</h1>

<%= render "form", survey_question: @survey_question %>

<br>

<div>
  <%= link_to "Show Survey Question", @survey_question %> |
  <%= link_to "Back to survey questions", survey_questions_path %>
</div>

app/views/survey_questions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Survey Questions</h1>

<div id="survey_questions">
  <% @survey_questions.each do |survey_question| %>
    <%= render survey_question %>
    <p>
      <%= link_to "Show this survey question", survey_question %>
    </p>
  <% end %>
</div>

<%= link_to "New survey_question", new_survey_question_path %>

app/views/survey_questions/new.html.erb
<h1>New Survey Question</h1>

<%= render "form", survey_question: @survey_question %>

<br>

<div>
  <%= link_to "Back to survey questions", survey_questions_path %>
</div>

app/views/survey_questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @survey_question %>

<div>
  <%= link_to "Edit this survey question", edit_survey_question_path(@survey_question) %> |
  <%= link_to "Back to survey questions", survey_questions_path %>

  <%= button_to "Destroy this survey question", @survey_question, method: :delete %>
</div>