config/routes.rb
Rails.application.routes.draw do

  resources :quizzes

  resources :quiz_questions, only: [], param: :index do
    member do
      delete '(:id)' => "quiz_questions#destroy", as: ""
      post '/' => "quiz_questions#create"
    end
  end

  resources :surveys

  resources :survey_questions, only: [], param: :index do
    member do
      delete '(:id)' => "survey_questions#destroy", as: ""
      post '/' => "survey_questions#create"
    end
  end

  resources :questions do
      get "search_by", on: :collection
  end

  root "pages#home"
end

app/models/survey.rb
class Survey < ApplicationRecord
    has_many :survey_questions, dependent: :destroy
    has_many :questions, :through => :survey_questions

    accepts_nested_attributes_for :survey_questions, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true


    validates :name, presence: true
    
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
    before_action :set_survey, only: %i[ show edit update destroy ]
  
    # GET /surveys or /surveys.json
    def index
      @surveys = Survey.all
    end
  
    # GET /surveys/1 or /surveys/1.json
    def show
      @survey_questions = SurveyQuestion.joins(:question).where(survey_id: params[:id])
    end
  
    # GET /surveys/new
    def new
      @survey = Survey.new(survey_questions: [SurveyQuestion.new])
      @questions = Question.all
    end
  
    # GET /surveys/1/edit
    def edit
    end
  
    # POST /surveys or /surveys.json
    def create
      @survey = Survey.new(survey_params)
      @questions = Question.all
      respond_to do |format|
        if @survey.save
          format.html { redirect_to survey_url(@survey), notice: "Survey was successfully created." }
          format.json { render :show, status: :created, location: @survey }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @survey.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /surveys/1 or /surveys/1.json
    def update
      respond_to do |format|
        if @survey.update(survey_params)
          format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
          format.json { render :show, status: :ok, location: @survey }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @survey.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /surveys/1 or /surveys/1.json
    def destroy
      @survey.destroy
  
      respond_to do |format|
        format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_survey
        @questions = Question.all
        @survey = Survey.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def survey_params
        params.require(:survey).permit(:name, :survey_survey_question, survey_questions_attributes: [:id, :points, :survey_id, :question_id, :_destroy ])
      end
  end
  

app/views/surveys/_form.html.erb
<%= form_with(model: survey) do |form| %>
  <% if survey.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-12 d-flex justify-content-end">
    <%= link_to "Back to Surveys", surveys_path, class: "btn btn-outline-primary" %>
  </div>
  <div>
    <%= form.label :name, style: "display: block", class: "fs-3" %>
    <%= form.text_field :name, class: "mb-5 form-control border border-secondary-subtle" %>
  </div>

  <h3>Questions</h3>
  <hr>
  <div id="survey_questions">
    <%= form.fields_for :survey_questions do |sq_form| %>
      <%= render "survey_questions/survey_questions", form: sq_form %>
    <% end %>
  </div>
  <%= form.submit "Add Question", 
      formaction: survey_question_path(@survey.survey_questions.size), 
      formmethod: :post, 
      formnovalidate: true, 
      id: "add-survey-question",
      class: "btn btn-outline-success" %>

   <div class="d-flex justify-content-start mb-3 mt-5">
    <%= form.submit class: "btn btn-primary fs-4 py-2" %>
  </div>

<% end %>

app/views/surveys/_news_survey_questions.html.erb
<% binding.pry %>
<%= form.hidden_field :id %>

<div>
  <%= form.label :description, style: "display: block" %>
  <%= form.text_field :description %>
</div>

app/views/surveys/_question_template.html.erb
<div>
    <hr>
  <%#Question Bank and Type%>
  <div class="d-flex justify-content-end pt-3 text-secondary" >
    <p>
      <strong>Question Type:</strong>
      <%= question.question_type.titleize %>
    </p>
  </div>
  
  <%#Question Title%>
  <div class="py-4">
    <h2>Question <%=index%>:</h2>
    <div class="fs-4">
      <%= question.title %>
    </div>
  </div>

  <%#Question Type Display%>
  <div class= "p-3">
    <% if question.true_false?%>
       <div class="alert <%= question.true_false.correct_answer? ? 'alert-success fw-bold' : 'alert-secondary' %>">
        True  
      </div>
      <div class="alert <%= question.true_false.correct_answer? ? 'alert-secondary' : 'alert-success fw-bold' %>">
        False 
      </div>
    <% end %>
    </div>
 
    <% if question.multiple_choice?%>
      <% question.multiple_choices.each do |choice|%>
        <%#questions/question_option for when it's rendered in quizzes%>
        <%= render "questions/question_option", choice: choice %>
      <%end%>
    <% end %>

    <% if question.multiple_answers?%>
      <% question.multiple_answers.each do |answer|%>
        <%#questions/question_option for when it's rendered in quizzes%>
        <%= render "questions/question_option", choice: answer %>
      <%end%>
    <% end %>

    <% if question.matching? %>
      <%#questions/matching_show for when it's rendered in quizzes%>
      <%= render "questions/matching_show", question: question%>
    <% end %>
  </div>

app/views/surveys/_survey.html.erb
<div id="<%= dom_id survey %>">
  <p class="fs-1 mb-5">
    <strong>Name:</strong>
    <%= survey.name %>
  </p>

  <% if @survey_questions.present? %>
    <h4 class="fs-2">Survey Questions</h4>
    <% @survey_questions.each_with_index do |survey_question, index| %>
      <div class="row container">
        <div class="col-12 mb-5">

          <%= render "question_template", question: survey_question.question, index: index + 1 %>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/surveys/edit.html.erb
<h1 class="mb-5 px-3">Editing Survey</h1>

<%= render "form", survey: @survey %>

<br>

app/views/surveys/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="pb-4">Surveys</h1>
  <%= link_to "New Survey", new_survey_path, class: "col btn btn-primary fs-4 mb-2" %>
<hr>


<div id="surveys">
  <% @surveys.each do |survey| %>
    <div class="card mb-5 shadow-sm d-flex">
      <div class="container py-3">
        <div class="row align-items-center">
          <div class=" fs-4 col-12 col-md-10 text-break">
            <p class="mb-0 me-3"><strong>Name:</strong> <%= survey.name %></p>
          </div>
          <div class="col-12 col-md text-end mt-3">
            <%= link_to "Show Survey", survey, class: " btn btn-success fs-5" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/surveys/new.html.erb
<h1 class="mb-5">New Survey</h1>

<%= render "form", survey: @survey, question: @question %>

<br>

app/views/surveys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @survey %>
<hr>

<div class="d-flex justify-content-around justify-content-md-start">
  <%= link_to "Edit Survey", edit_survey_path(@survey), class: "fs-4 btn btn-outline-primary" %>
  <%= link_to "Back to Surveys", surveys_path, class: "fs-4 ms-4 btn btn-outline-primary" %>
</div>
<div class="d-flex justify-content-end mb-5 mt-5 mt-md-0 me-3">
  <%= button_to "Delete Survey", @survey, method: :delete, class: "col btn btn-outline-danger fs-5 mt-3" %>
</div>