config/routes.rb
Rails.application.routes.draw do

  resources :quizzes

  resources :quiz_questions, only: [], param: :index do
    member do
      delete '(:id)' => "quiz_questions#destroy", as: ""
      post '/' => "quiz_questions#create"
    end
  end

  resources :surveys

  resources :survey_questions, only: [], param: :index do
    member do
      delete '(:id)' => "survey_questions#destroy", as: ""
      post '/' => "survey_questions#create"
    end
  end

  resources :questions do
      get "search_by", on: :collection
  end

  root "pages#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorProjectStarter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">

        <%= link_to root_path, class:"navbar-brand link-primary" do %><i class="bi bi-question-diamond-fill me-2"></i>QUIZ'EM<% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
            <li class="nav-item">
              <%= link_to "New Question", new_question_url, class: "nav-link ps-4" %>
            </li>
            <li class="nav-item">
              <%= link_to "Question", questions_url, class: "nav-link ps-4" %>
            </li>
            <li class="nav-item">
              <%= link_to "Quizzes", quizzes_url, class: "nav-link ps-4" %>
            </li>
            <li class="nav-item">
              <%= link_to "Surveys", surveys_url, class: "nav-link ps-4" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    
    <div class="container pt-5">
      <%= yield %>
    </div>

    <footer class="container-fluid p-5 text-center bg-dark text-light mt-auto w-100">
      &copy; powered by Rails - All rights reserved
    </footer>
    
  </body>
</html>